config/routes.rb
Rails.application.routes.draw do

  get 'products/new'

  get 'products/edit'

  get 'products/show'

  get 'password_resets/new'

  get 'password_resets/edit'

  get '/about', :to => 'pages#about'
  get '/contact', :to => 'pages#contact'
  get '/feature', :to => 'pages#featured'
  get '/promo', :to => 'pages#promos'

  get '/signup', :to => 'users#new'
  get '/login', :to => 'sessions#new'
  post 'login', :to => 'sessions#create'
  get '/logout', :to => 'sessions#destroy'

  resources :users
  resources :sessions
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :products

root 'pages#index'

end

app/views/partial/_footer.html.erb
  <footer class="footer">
    <div class="navbar navbar-default navbar-fixed-bottom" role="navigation" >
      <div class="container">
        <p class="text-muted">Copyright © 2015 by <%= link_to "Androbotics Clark Inc,", 'http://androbotest.t15.org/androboticsclark/' %>. All Rights Reserved.</p>
      </div>
    </div>
  </footer>
</div>

app/views/partial/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kuwarto</title>
  <link rel="stylesheet" type="text/css" href="/assets/bootstrap.css">
  <link rel="stylesheet" type="text/css" href="/assets/application.css">
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
  <script src="/assets/jquery.js"></script>
  <script src="/assets/bootstrap.js"></script>
</head>
<body>
<nav class = "navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%=link_to image_tag("logo.png", :border => 0), root_path, {:class => "navbar-brand", :alt =>"Brand"} %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav nav-pills navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>

        <% if current_user.try(:admin?) %>
        <li><%= link_to "Users", users_path %></li>
        <% end %>

        <% if logged_in? %>
          <li><%= link_to "Post an Ad", new_product_path %></li>
          <li class="dropdown" role="presentation">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Account<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", '#' %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Register", signup_path %></li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>